[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<*> -<main_hw454b.cpp> -<main_scan.cpp>
lib_deps =
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    bblanchon/ArduinoJson
    links2004/WebSockets

[env:hw454b]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<*> -<main.cpp> -<main_scan.cpp>
build_flags =
    -DOLED_SDA=21
    -DOLED_SCL=22
lib_deps =
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    bblanchon/ArduinoJson
    links2004/WebSockets

[env:native]
platform = native
build_src_filter = +<*> -<main_hw454b.cpp> -<main_scan.cpp>
lib_deps =
    bblanchon/ArduinoJson
